apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
  ssl-cert.pem: {{ tpl (.Files.Get "config/ssl-cert.pem") . | quote }}